### ISSUE TITLE
Build failed on windows

### ISSUE THREAD

**Issue by heiha100** [hwkim1127/simple_native_image_compress#2]
**enviroments:**
flutter version: 3.19.2
windows version: Windows 11 Professional 22H2 

**error msg:**
`
[        ]   SEVERE : Cargokit BuildTool failed with error :
[C:\work\flutter\androp\build\windows\x64\plugins\simple_native_image_compress\simple_native_image_compress_cargokit.vcxproj]
[        ]   C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(254,5): error MSB8066: Custom build for
'C:\work\flutter\androp\build\windows\x64\CMakeFiles\d2cadfdd70b453df3c30d8e1388e44e4\native_image_compress.dll.rule;C:\work\flutter\androp\build\windows\x64\CMakeFiles\e6a54e3983
6c32c0b6f5f3d9c57e0960\simple_native_image_compress_cargokit.rule' exited with code -1.
[C:\work\flutter\androp\build\windows\x64\plugins\simple_native_image_compress\simple_native_image_compress_cargokit.vcxproj]
`

**Comment by heiha100** [comment]
Oh, I haven't configured Rust correctly. Sorry for bothering you.

**Comment by hwkim1127** [comment]
I think I should probably add how to set up rust...
thanx!
