### ISSUE TITLE
Can't specify format of input image

### ISSUE THREAD

**Issue by adg-mh** [hwkim1127/simple_native_image_compress#4]
I've run into an issue where iOS is sharing out screenshots with a `.jpeg` extension, but the file is actually a `.png`.
simple_native_image_compress doesn't seem to allow providing the format of the input image.
Without the ability to specify the decode format there are certain scenarios where the file must be copied and then cleaned up, which I'd like to avoid.

Is it possible to support specifying the decode format?

**Comment by hwkim1127** [comment]
hi can you upload the original image file and provide the error message you encountered?
also, image file format should be detected automatically by the `rust image crate` unless image is created with some wierd metadata.
Thus, currently I am not trying to include decode format at the moment.

**Comment by adg-mh** [comment]
You can reproduce the error by renaming any png to jpeg and trying to compress it:
The error reads: `Failed to convert image: FrbAnyhowException(Format error decoding Jpeg: invalid JPEG format: first two bytes are not an SOI marker`

According to the [image crate docs](https://docs.rs/image/latest/image/fn.open.html) for image::open the format is determined by the file extension. It appears that this is what simple_native_image_compress uses to load the images. I'm running into cases where images have the wrong extension, but I still need to attempt to process them.

ImageReader does also include a [with_guessed_format](https://docs.rs/image/latest/image/struct.ImageReader.html#method.with_guessed_format) method, which if able to use would solve my use case.


Edit: I am able to determine the file type using the headers of the image, so either the ability to specify the format or use `with_guessed_format` would help.

Currently I'm copying the file (which can be slow), as I won't want to rename the user's files.

**Comment by hwkim1127** [comment]
just updated the package to use guessed format. should be fine now if you use package version 2.0.2

**Comment by hwkim1127** [comment]
just updated the package to use guessed format. If you update your package version to 2.0.2. It should be fine now.
