### ISSUE TITLE
cargokit shell scripts in the 2.0.2 package have CRLF line endings, causing error building for ios on mac

### ISSUE THREAD

**Issue by adg-mh** [hwkim1127/simple_native_image_compress#5]
The cargokit shell scripts in the 2.0.2 package on pub.dev seem to have CRLF line endings. This is causing an error during build on macos (when building for ios):

```
build_pod.sh: line 2: set: -
: invalid option
    set: usage: set [--abefhkmnptuvxBCHP] [-o option] [arg ...]
    Command PhaseScriptExecution failed with a nonzero exit code
```

If I replace the line endings with LF in `cargokit\run_build_tool.sh` and `cargokit\build_pod.sh` before building the error is avoided.

**Comment by hwkim1127** [comment]
it's a stupid problem caused by windows. I will update the library from Linux.

**Comment by hwkim1127** [comment]
just pushed the package version 2.0.3
should have been fixed.
