### ISSUE TITLE
Support for AVIF

### ISSUE THREAD

**Issue by JoshiJoshiJoshi** [hwkim1127/simple_native_image_compress#6]
First of all thanks for the work so far. I would like to ask whether it is planned to support the image format avif in the near future :)

**Comment by hwkim1127** [comment]
I just checked whether the rust image crate supports avif or not. Since the library supports it, I will add support for the next release.

**Comment by hwkim1127** [comment]
Actullay, for AVIF, C code is required so cross compilation is not possible, unless using zig...
so I don't think it will be supported in the near future. unless I recreate this library with zig...

**Comment by hwkim1127** [comment]
Actullay, for AVIF, C code is required so cross compilation is not possible, unless using zig...
so I don't think it will be supported in the near future. unless I recreate this library with zig...

**Comment by hwkim1127** [comment]
sorry my bad. the next release 2.3.0 will support AVIF as compression format.

**Comment by hwkim1127** [comment]
2.3.0 released. closing
